### ISSUE TITLE
invalid multibyte char (US-ASCII) (SyntaxError)

### ISSUE THREAD

**Issue by baditaflorin** [joto/taginfo#140]
./taginfo.rb 8081
<internal:lib/rubygems/custom_require>:29:in `require': /usr/local/lib/ruby/gems/1.9.1/gems/r18n-core-2.0.4/lib/r18n-core/locale.rb:179: invalid multibyte char (US-ASCII) (SyntaxError)
/usr/local/lib/ruby/gems/1.9.1/gems/r18n-core-2.0.4/lib/r18n-core/locale.rb:179: invalid multibyte char (US-ASCII)
/usr/local/lib/ruby/gems/1.9.1/gems/r18n-core-2.0.4/lib/r18n-core/locale.rb:179: syntax error, unexpected $end, expecting keyword_end
      str[0] = '−' if 0 > integer # Real typographic minus
                  ^
        from <internal:lib/rubygems/custom_require>:29:in `require'
        from /usr/local/lib/ruby/gems/1.9.1/gems/r18n-core-2.0.4/lib/r18n-core.rb:25:in `<top (required)>'
        from <internal:lib/rubygems/custom_require>:29:in `require'
        from <internal:lib/rubygems/custom_require>:29:in `require'
        from /usr/local/lib/ruby/gems/1.9.1/gems/sinatra-r18n-2.0.4/lib/sinatra/r18n.rb:21:in `<top (required)>'
        from <internal:lib/rubygems/custom_require>:33:in `require'
        from <internal:lib/rubygems/custom_require>:33:in `rescue in require'
        from <internal:lib/rubygems/custom_require>:29:in `require'
        from ./taginfo.rb:46:in `<main>'

**Comment by joto** [comment]
I remember something about some broken versions of the r18n library. Try installing an older or newer version.

**Comment by lonvia** [comment]
You need to use rack in version 1.4.5 and sinatra-r18n in a version < 2.0. Make sure to uninstall the newer versions of both packages or taginfo will use the wrong ones.

**Comment by joto** [comment]
Looks like this https://github.com/ai/r18n/issues/122 might be the issue here. Although I would expect rubygems not to install a version of a gem that doesn't work with the ruby version i installs it for.

**Comment by joto** [comment]
Also see https://lists.openstreetmap.org/pipermail/taginfo-dev/2015-May/thread.html.

**Comment by dieterdreist** [comment]
I confirm this is still an issue. Using these versions like described [here](https://lists.openstreetmap.org/pipermail/taginfo-dev/2015-May/000231.html) solved it for me:
sudo gem install rack         -v 1.4.5
sudo gem install r18n-core    -v 1.1.11
sudo gem install sinatra-r18n -v 1.1.11
